/**
 * 一次性 generator：从 iching-shifa (MIT) 提取 GUA_DESCRIPTIONS → 写 db/seed/gua64.ts
 *
 * 用法：bunx tsx scripts/generate-gua64.ts （或 pnpm tsx scripts/generate-gua64.ts）
 *
 * 设计：
 *   - 64 卦繁简归一（iching-shifa 原表混用 繁/简，统一到简体规范名）
 *   - 8 trigram 严格枚举：乾 兑 离 震 巽 坎 艮 坤
 *   - 每卦输出 {name, upper, lower, pan_ci, yao_ci(JSON 字符串 6 行), tuan_ci}
 *
 * 防御 #20（plan §M3.16）：开源 json 起手，手修 20% 调风格 — 这一步先 1:1 落库，
 * 后续 task M3.17+ 按 prompt 灌入时再批量 LLM 改写温柔风格。
 */
import * as iching from "iching-shifa";
import * as fs from "node:fs";
import * as path from "node:path";

type Trigram = "乾" | "兑" | "离" | "震" | "巽" | "坎" | "艮" | "坤";

// 64 卦：从 iching-shifa GUA64_ORDER 的 raw name → 归一简体名 + (upper, lower)
//
// 顺序按京房八宫卦序（与 GUA64_ORDER 一致）。entry: [rawName, canonicalName, upper, lower]
const GUA64_TABLE: ReadonlyArray<readonly [string, string, Trigram, Trigram]> = [
  // 宫 0 乾 (上乾)
  ["乾", "乾", "乾", "乾"],
  ["姤", "姤", "乾", "巽"],
  ["遯", "遁", "乾", "艮"],
  ["否", "否", "乾", "坤"],
  ["观", "观", "巽", "坤"],
  ["剝", "剥", "艮", "坤"],
  ["晉", "晋", "离", "坤"],
  ["大有", "大有", "离", "乾"],
  // 宫 1 震 (上震)
  ["震", "震", "震", "震"],
  ["豫", "豫", "震", "坤"],
  ["解", "解", "震", "坎"],
  ["恆", "恒", "震", "巽"],
  ["升", "升", "坤", "巽"],
  ["井", "井", "坎", "巽"],
  ["大过", "大过", "兑", "巽"],
  ["随", "随", "兑", "震"],
  // 宫 2 坎 (上坎)
  ["坎", "坎", "坎", "坎"],
  ["节", "节", "坎", "兑"],
  ["屯", "屯", "坎", "震"],
  ["既济", "既济", "坎", "离"],
  ["革", "革", "兑", "离"],
  ["豐", "丰", "震", "离"],
  ["明夷", "明夷", "坤", "离"],
  ["師", "师", "坤", "坎"],
  // 宫 3 艮 (上艮)
  ["艮", "艮", "艮", "艮"],
  ["贲", "贲", "艮", "离"],
  ["大畜", "大畜", "艮", "乾"],
  ["损", "损", "艮", "兑"],
  ["睽", "睽", "离", "兑"],
  ["履", "履", "乾", "兑"],
  ["中孚", "中孚", "巽", "兑"],
  ["漸", "渐", "巽", "艮"],
  // 宫 4 坤 (上坤)
  ["坤", "坤", "坤", "坤"],
  ["复", "复", "坤", "震"],
  ["临", "临", "坤", "兑"],
  ["泰", "泰", "坤", "乾"],
  ["大壮", "大壮", "震", "乾"],
  ["夬", "夬", "兑", "乾"],
  ["需", "需", "坎", "乾"],
  ["比", "比", "坎", "坤"],
  // 宫 5 巽 (上巽)
  ["巽", "巽", "巽", "巽"],
  ["小畜", "小畜", "巽", "乾"],
  ["家人", "家人", "巽", "离"],
  ["益", "益", "巽", "震"],
  ["无妄", "无妄", "乾", "震"],
  ["噬嗑", "噬嗑", "离", "震"],
  ["颐", "颐", "艮", "震"],
  ["蛊", "蛊", "艮", "巽"],
  // 宫 6 离 (上离)
  ["离", "离", "离", "离"],
  ["旅", "旅", "离", "艮"],
  ["鼎", "鼎", "离", "巽"],
  ["未济", "未济", "离", "坎"],
  ["蒙", "蒙", "艮", "坎"],
  ["渙", "涣", "巽", "坎"],
  ["讼", "讼", "乾", "坎"],
  ["同人", "同人", "乾", "离"],
  // 宫 7 兑 (上兑)
  ["兑", "兑", "兑", "兑"],
  ["困", "困", "兑", "坎"],
  ["萃", "萃", "兑", "坤"],
  ["咸", "咸", "兑", "艮"],
  ["蹇", "蹇", "坎", "艮"],
  ["谦", "谦", "坤", "艮"],
  ["小过", "小过", "震", "艮"],
  ["归妹", "归妹", "震", "兑"],
] as const;

if (GUA64_TABLE.length !== 64) {
  throw new Error(`期望 64 行，实际 ${GUA64_TABLE.length}`);
}

const order = (iching.GUA64_ORDER as readonly string[]) ?? [];
if (order.length !== 64) {
  throw new Error(`iching-shifa GUA64_ORDER 不是 64 项：${order.length}`);
}

// 校验 raw name 与 GUA64_ORDER 顺序一致
for (let i = 0; i < 64; i++) {
  if (GUA64_TABLE[i]![0] !== order[i]) {
    throw new Error(`#${i} 不匹配：表 ${GUA64_TABLE[i]![0]} ≠ iching ${order[i]}`);
  }
}

const descs = (iching as unknown as {
  GUA_DESCRIPTIONS: Record<string, Record<string, string>>;
}).GUA_DESCRIPTIONS;

interface Gua64Entry {
  name: string;
  upper: Trigram;
  lower: Trigram;
  pan_ci: string;
  yao_ci: string; // JSON-stringified 6-string array
  tuan_ci: string;
}

const entries: Gua64Entry[] = GUA64_TABLE.map(([raw, canonical, upper, lower]) => {
  const d = descs[raw];
  if (!d) throw new Error(`iching-shifa 缺 ${raw} 的 GUA_DESCRIPTIONS`);
  const yaoArr: string[] = [];
  for (let i = 1; i <= 6; i++) {
    const yao = d[String(i)];
    if (!yao) throw new Error(`${raw} 缺第 ${i} 爻`);
    yaoArr.push(yao.trim());
  }
  return {
    name: canonical,
    upper,
    lower,
    pan_ci: (d["0"] ?? "").trim(),
    yao_ci: JSON.stringify(yaoArr),
    tuan_ci: (d["7"] ?? "").trim(),
  };
});

// 写 db/seed/gua64.ts
const out = `// AUTO-GENERATED by scripts/generate-gua64.ts (M3.16)
// Source: iching-shifa@1.2.0 (MIT, https://github.com/kentang2017/iching_shifa)
//
// 字段：
//   - name      简体卦名
//   - upper     上卦（8 trigram 之一）
//   - lower     下卦（同上）
//   - pan_ci    卦辞
//   - yao_ci    JSON.stringify 后的 6 爻爻辞数组
//   - tuan_ci   彖辞（解释，AI 解读时拼进 prompt）
//
// 防御 #20：原 panci/yaoci 是文言原文，AI 解读 prompt 里再做温柔化包装；
// 字典本身保留原文便于校对。
export type Trigram = "乾" | "兑" | "离" | "震" | "巽" | "坎" | "艮" | "坤";

export interface Gua64Entry {
  name: string;
  upper: Trigram;
  lower: Trigram;
  pan_ci: string;
  yao_ci: string;
  tuan_ci: string;
}

export const GUA64: ReadonlyArray<Gua64Entry> = ${JSON.stringify(entries, null, 2)};

export const TRIGRAMS = ["乾", "兑", "离", "震", "巽", "坎", "艮", "坤"] as const;

/** 按上下卦组合查找 */
export function findGuaByTrigrams(upper: Trigram, lower: Trigram): Gua64Entry | undefined {
  return GUA64.find((g) => g.upper === upper && g.lower === lower);
}

/** 按名字查找 */
export function findGuaByName(name: string): Gua64Entry | undefined {
  return GUA64.find((g) => g.name === name);
}
`;

const outPath = path.resolve(process.cwd(), "db/seed/gua64.ts");
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out, "utf8");
console.log(`已写入 ${outPath} (${entries.length} entries)`);
